### ISSUE TITLE
Other Examples

### ISSUE THREAD

**Issue by razzraziel** [OskarSigvardsson/unity-delaunay#1]
Hi, great destruction effect on cubic meshes but couldnt figure it out how to use it on cylinder for example. Is is possible? What classes in plugin folder are for? Should we call some functions inside of them to BreakableSurface.cs ?

**Comment by OskarSigvardsson** [comment]
On cylinders specifically, it's doable, but it's more complicated

The way this effect work is by generating 2d voronoi diagrams and then breaking the meshes in that shape. You could do that on curved surfaces, especially a cylinder. But figuring out how the meshes are supposed be generated is more complicated. 

The classes in the Plugin folder is the core of the algorithm, those are the classes that generate the Voronoi tessellations and clip them to arbitrary shapes. The rest of the code I just put together fairly quickly to demonstrate the principle. 

If you want to try and do this for real in a game, you should know that the limiting factor is the physics. Shards either need to disappear really quickly, or you need to in some other way prevent them from interacting weirdly. 

If you're interested in destruction of arbitrary shapes, I did another thing, here: https://github.com/OskarSigvardsson/quickfracture

That idea had more promise and I could probably have gotten it somewhere, but life came in the way and I basically abandonded it. Maybe some day I'll pick it back up again. That repo as it stands now is a bit messy.

**Comment by razzraziel** [comment]
thank you, you have great projects. i'll look into these.

**Comment by OskarSigvardsson** [comment]
Good luck!
