### ISSUE TITLE
Shards just disappear?

### ISSUE THREAD

**Issue by oxi-dev0** [OskarSigvardsson/unity-delaunay#4]
When using this script, the shards just disappear? instead of falling like in the gif. any help would be appreciated!

**Comment by OskarSigvardsson** [comment]
@X0FloH i just tried it out again (for the first time in a couple of years) and it still works just fine. You'll have to give me a more specific bug report if you want me to investigate what's going on. If you can provide some more details on what's happening, I'll consider reopening and investigating.
